# Generated by Django 5.1 on 2024-08-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='image',
            field=models.TextField(),
        ),
    ]
