# Generated by Django 5.1 on 2024-08-12 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_touristplace_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristplace',
            name='user',
        ),
        migrations.AddField(
            model_name='touristplace',
            name='user',
            field=models.ManyToManyField(related_name='places', to=settings.AUTH_USER_MODEL),
        ),
    ]
