# Generated by Django 5.1 on 2024-08-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_remove_touristplace_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='description_place',
            field=models.TextField(blank=True, null=True),
        ),
    ]
