# Generated by Django 5.1 on 2024-08-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_touristplace_description_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='languages',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='regions',
            field=models.CharField(blank=True, null=True),
        ),
    ]
