# Generated by Django 5.1 on 2024-08-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_alter_touristplace_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='regions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
