# Generated by Django 5.1 on 2024-08-17 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_alter_touristplace_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
