# Generated by Django 5.1 on 2024-08-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_touristplace_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
