# Generated by Django 5.1 on 2024-08-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_touristplace_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristplace',
            old_name='location',
            new_name='destination_tourist',
        ),
    ]
