# Generated by Django 5.1 on 2024-08-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_rename_location_touristplace_destination_tourist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristplace',
            old_name='destination_tourist',
            new_name='location',
        ),
    ]
